language: python

python:
- 2.7
- 3.4
- 3.5
- 3.6

install:
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install -e .[travis]

script:
  coverage run setup.py test

after_success:
  coveralls

notifications:
- email: false

before_deploy:
- python setup.py sdist
- python setup.py bdist_wheel
- python setup.py bdist_wheel --universal
- python setup.py egg_info

deploy:
- provider: pypi
  user: jonathandekhtiar
  password: "$PYPI_PASSWORD"
  skip_cleanup: true
  on:
    tags: true
    python: '3.6'

- provider: releases
  file:
  - dist/*
  - python3_linkedin.egg-info/PKG-INFO
  file_glob: true
  skip_cleanup: true
  api_key: "$GITHUB_PERSONAL_TOKEN"
  on:
    tags: true
    python: '3.6'
